# frozen_string_literal: true

# Rake tasks for importing SRD (System Reference Document) data from JSON files
# generated by the Python PDF parser.
#
# Usage:
#   rails srd:import[2024]           # Import all content for 2024 edition
#   rails srd:import[2014]           # Import all content for 2014 edition
#   rails srd:import_type[monsters,2024]  # Import only monsters for 2024 edition
#   rails srd:clean[2024]            # Remove all content for 2024 edition
#
namespace :srd do
  desc 'Import all SRD data from JSON files for a specific edition'
  task :import, [:edition] => :environment do |_t, args|
    edition = args[:edition] || '2024'
    json_dir = Rails.root.join('scripts', 'srd_parser', 'output', edition)

    unless json_dir.exist?
      puts "Error: JSON directory not found at #{json_dir}"
      puts 'Run the Python parser first to generate JSON files.'
      exit 1
    end

    importer = SrdImporter.new(json_dir, edition)
    importer.import_all

    puts "SRD import complete for edition #{edition}"
  end

  desc 'Import a specific content type from JSON for a specific edition'
  task :import_type, %i[type edition] => :environment do |_t, args|
    type = args[:type]
    edition = args[:edition] || '2024'

    if type.blank?
      puts 'Error: Please specify a content type'
      puts "Available types: #{SrdImporter::CONTENT_TYPES.join(', ')}"
      exit 1
    end

    json_dir = Rails.root.join('scripts', 'srd_parser', 'output', edition)

    unless json_dir.exist?
      puts "Error: JSON directory not found at #{json_dir}"
      exit 1
    end

    importer = SrdImporter.new(json_dir, edition)
    count = importer.import_type(type)

    puts "Imported #{count} #{type} records for edition #{edition}"
  end

  desc 'Clean all SRD data for a specific edition'
  task :clean, [:edition] => :environment do |_t, args|
    edition = args[:edition]

    if edition.blank?
      puts 'Error: Please specify an edition to clean (2014 or 2024)'
      exit 1
    end

    puts "WARNING: This will delete all SRD content for edition #{edition}"
    puts 'Press Ctrl+C to cancel, or Enter to continue...'
    $stdin.gets

    models = [
      Rule, Monster, Spell, DndClass, Race, Item, Condition, Section, Skill, AbilityScore, Prof
    ]

    models.each do |model|
      count = model.where(edition: edition).count
      model.where(edition: edition).destroy_all
      puts "Deleted #{count} #{model.name} records"
    end

    puts "Clean complete for edition #{edition}"
  end

  desc 'List available editions and content counts'
  task status: :environment do
    editions = %w[2014 2024]
    models = {
      'Rules' => Rule,
      'Monsters' => Monster,
      'Spells' => Spell,
      'Classes' => DndClass,
      'Races' => Race,
      'Items' => Item,
      'Conditions' => Condition,
      'Sections' => Section,
      'Skills' => Skill,
      'Ability Scores' => AbilityScore,
      'Proficiencies' => Prof
    }

    puts "\nSRD Content Status"
    puts '=' * 50

    editions.each do |edition|
      puts "\nEdition: #{edition}"
      puts '-' * 30

      models.each do |name, model|
        count = model.where(edition: edition).count
        puts format('  %-15s %5d', name, count)
      end
    end

    puts "\n"
  end
end
