Metrics/ClassLength:
  CountComments: false
  Max: 235

Documentation:
  Enabled: false

EmptyLines:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 150
  Exclude:
    - 'config/routes.rb'

MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/PerceivedComplexity:
  # http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/PerceivedComplexity
  Max: 8
